### ISSUE TITLE
Errors building dotstats common package

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/dotstats#20] opened 2018-07-25 06:03 UTC
I've modified the common package to export another utility function, but I need to build the common package in order for other files to import from it.

When I try and build the common package by running `yarn build:common`, I get the following output:
```
$ yarn build:common
yarn run v1.7.0
$ tsc -p packages/common
error TS5055: Cannot write file '/Users/Me/code/blockchain/clones/paritytech/dotstats/packages/common/build/feed.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/Me/code/blockchain/clones/paritytech/dotstats/packages/common/build/helpers.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/Me/code/blockchain/clones/paritytech/dotstats/packages/common/build/id.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/Me/code/blockchain/clones/paritytech/dotstats/packages/common/build/index.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/Me/code/blockchain/clones/paritytech/dotstats/packages/common/build/types.d.ts' because it would overwrite input file.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I remove `"declaration": true` from packages/common/tsconfig.json no errors are produced but I still can't import the new exported functions. I also tried adding the following to the tsconfig.json (if this makes any sense) but it still produces the errors:
```
"exclude": [
  "build/**/*.d.ts"
]
```

**Comment by maciejhirsz** [comment] 2018-07-25 17:03
@ltfschoen can't reproduce, bother me about this tomorrow morning :)

**Comment by maciejhirsz** [comment] 2018-07-27 13:01
We figured this out, so closing the issue.

**Closed by maciejhirsz** 2018-07-27 13:01 UTC
